tools/vardictjava.cwl

Disabled verbose logging for vardict.  Logs for some intervals were approaching 19GB +

:heavy_minus_sign: removed verbose flag as log sizes get out of had

---

dev/cnv_using_subwf_test.cwl
sub_workflows/kfdrc_run_theta2_sub_wf.cwl
tools/cnvkit_import_theta2.cwl
tools/theta2_purity.cwl
workflow/kfdrc_cnvkit_plus_theta2.cwl
workflow/kfdrc_combined_somatic_wgs_cnv_wf.cwl
workflow/kfdrc_production_WGS_somatic_variant_cnv.cwl

Solves issue when Theta2 fails, the whole WF is tanked.  Instead, it will just have null outputs as cnvkit outputs without theta2 adjustments are still valid.  See ticket: https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/kids-first/kf-genomics-harmonization/466

Mb catch theta2 error

---

sub_workflows/kfdrc_lancet_sub_wf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
sub_workflows/kfdrc_vardict_sub_wf.cwl
workflow/kfdrc_production_WES_somatic_variant_cnv_wf.cwl
workflow/kfdrc_production_WGS_somatic_variant_cnv.cwl

Based on a feature request from our Australian collaborators, allow to specify ref version for VEP step. Tested on hg37 SBG test files for [WGS](https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/f829f182-1f61-43aa-9710-0e10d7c446f7/) and [WES](https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/636a84ac-ff68-438d-bc1c-a6c96efdc2f8/).

:hammer: added ability to specify VEP reference version

---

README.md
sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_mutect2_filter_support_subwf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
tools/gatk_filtermutectcalls.cwl
tools/gatk_getpileupsummaries.cwl
tools/index_references.cwl
tools/manta.cwl
tools/strelka2.cwl
workflow/kfdrc_somatic_caller_workflow.cwl

Added ability to specify VEP ref version. Also fixed a reference_dict bug - was specified at wf level, but not sub wf level, causing failures to get reference_dict running mutect2. Also renamed strelka bed input var to be more accurate.

Mb open vep ref port

---

workflow/kfdrc_production_WES_somatic_variant_cnv_wf.cwl
workflow/kfdrc_production_WGS_somatic_variant_cnv.cwl

@zhangb1 found a bug where production exome wf strelak2 and mutect2 callers bot actually running in exome mode. After looking into it I have found that:
if you look at the job.json, you see this:
`"exome_flag" : "Y",`
and it behaves as expected
but the strelka2 sub wf passed with to strelka2:
`"exome_flag" : "${return \"Y\";}",`
To fix this, I have instead set a `default` value at the top wf level in both WGS (which was accidentally running properly) and WES production workflows.  Bo has run a test here:
https://cavatica.sbgenomics.com/u/d3b-bixu/rs-14jwqpdg-pnoc003-omics-analysis/tasks/f8a6d056-c514-44ab-86c7-32d7451d0032/

Mb fix exome flag

---

.gitignore
tools/normalize_vcf.cwl

Issue explained in dev ticket:
https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/527
Successful correct input run, old VEP info stripped and file normed:
https://cavatica.sbgenomics.com/u/d3b-bixu/dev-wgsa/tasks/577c36d8-7fb4-4516-bfd4-6c6025a9fa48/
Successful incorrect input run, old VEP info remains, but file is still normed:
https://cavatica.sbgenomics.com/u/d3b-bixu/dev-wgsa/tasks/dd36b20a-7d62-4df4-82c6-483147d415a7/

:wrench: added bug fix to norm step discovered during WGSA work

---

.github/PULL_REQUEST_TEMPLATE.md
tools/bedtools_intersect.cwl
tools/gatk_intervallisttool.cwl
tools/mode_defaults.cwl
tools/mode_selector.cwl
tools/preprocess_lancet_intervals.cwl
tools/python_vardict_interval_split.cwl
workflow/kfdrc_production_WES_somatic_variant_cnv_wf.cwl
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl

This PR creates minimal workflow that can run both WGS and WXS versions of the kfdrc production somatic workflow per https://github.com/d3b-center/bixu-tracker/issues/593.
General description of changes:
- Added functionality to preprocess_lancet_intervals and gatk_intervallisttool to skip the step if the input is not provided. This was needed on account of this lancet interval preprocessing only occuring in WGS. The pass through allows WXS to go through these steps without failure.
- Created two new tools to handle defaults and mode specific files. mode_defaults simply rescues the default functionality that is lost when we were able to specify defaults specific to WGS and WXS. mode_selector is for instances where WGS and WXS disagree on which file to pass to a subsequent step. The tool …

🤝 WGS and WXS WFs United

---

sub_workflows/prepare_reference.cwl
tools/bundle_secondaryfiles.cwl
tools/bwa_index.cwl
tools/gatk_indexfeaturefile.cwl
tools/picard_createsequencedictionary.cwl
tools/samtools_faidx.cwl
tools/tabix_index.cwl
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl

This update changes the way reference inputs and their indexes are handled in the somatic workflow. Rather than having indexes be passed as secondaryFiles, they can be optionally provided as their own inputs. If indexes are not provided an indexing step will occur for their main file. This change resolves issues with passing secondaryFiles to users using Cavatica suggested file links.
Resolves https://github.com/d3b-center/bixu-tracker/issues/670
* Environment: cwltool 3.0.20200324120055, Cavatica
* Test files: see Cavatica test

🌐 optionally index inputs

---

tools/bwa_index.cwl

Bug discovered in my alignment runs in the bwa index tool. Listing input_alt twice generates a javascript error. This fixes that error
* Environment: Cavatica
* Test files: see Cavatica test

🔧 fix double alt listing

---

tools/bwa_index.cwl

BWA index will generate the indexes in the directory of the file it is indexing. This presents problems in two ways:
1. In cwltool that is a readonly env and will throw a segmentation fault
1. glob cannot access the files there

🐛 bwa index bug

---

tools/preprocess_lancet_intervals.cwl

This PR fixes the erroneously id'd preprocess_lancet_intervals.cwl file. 
Closes https://github.com/d3b-center/bixu-tracker/issues/759
Cosmetic change that requires no testing.

🐛 rename id

---

sub_workflows/kfdrc_lancet_sub_wf.cwl
sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_mutect2_filter_support_subwf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_vardict_sub_wf.cwl
tools/gatk_getpileupsummaries.cwl
tools/gatk_learnorientationbias.cwl
tools/manta.cwl
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl

This PR contains various changes to combat memory issues running large samples through the workflow. The workflow now allows the user max memory for the following tools at task creation:
- GATK GetPileupSummaries
- GATK LearnReadOrientationModel
Additionally, the user can adjust the memory allocation for Manta. Manta works differently than the Java GATK tools in that it's max memory isn't capped by a java option. Manta's max memory simply indicates what allocation of a VM will be saved for its running. When the task actually runs it may go over that cap and cause memory issues.
Finally, in order to allow Manta to scale beyond the memory allocated by a c5.9xlarge VM we had to remove the instance type restriction from the top level workflow. This restriction was added back at the …

🧠 Memory Tweeking

---

sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
tools/gatk_filtermutectcalls.cwl
workflow/kfdrc_production_manta_wf.cwl
workflow/kfdrc_production_mutect2_wf.cwl
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl

- memory changes for the somatic workflow now exposing gatk FilterMutectCalls.
- bringing the standalone workflows up to date with the changes to the main workflow.
- expose cpu option for manta as lowering cores could potentially cap memory usage in extreme cases
* Environment: Cavatica
* Test files: see revision 5 tasks

🧠 expose memory and cpu hooks

---

tools/ubuntu_ratio2seg.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Sets shellQuote to true in ubuntu_ratio2seg.cwl python -c argument. This block is supposed to be quoted as python -c takes a string input. Cavatica will default shellQuote to false and cause this tool to fail.
Closes https://github.com/d3b-center/bixu-tracker/issues/833
* Environment: Cavatica, cwltool 3.0.20200807132242
* Test files: See Cavatica test

🐛 quote python -c script

---

workflow/kfdrc_production_cnvkit_wf.cwl
workflow/kfdrc_production_controlfreec_wf.cwl
workflow/kfdrc_production_lancet_wf.cwl
workflow/kfdrc_production_manta_wf.cwl
workflow/kfdrc_production_mutect2_wf.cwl
workflow/kfdrc_production_strekla2_wf.cwl
workflow/kfdrc_production_theta2_wf.cwl
workflow/kfdrc_production_vardict_wf.cwl

The per-tool workflows inherited the resource requirements of the production workflow. However, at this level it leads to lots of unused cores and memory and increased calls. I've removed the instance hint at the wf level and reduced parallel instance counts to scale this back a bit. Fixes # (issue)
* Environment:
* Test files:

🏇 Scaled back some hints for per-tool wfs. Too aggressive!

---

sub_workflows/kfdrc_controlfreec_sub_wf.cwl
tools/ubuntu_rename_outputs.cwl
workflow/kfdrc_production_controlfreec_wf.cwl

Updated standalone ControlFreeC app to accept a `.mappability` file created using gem, `.cpn` files for fast re-processing of previous results, and `min_subclone_presence` inputs to allow for ControlFreeC to calculate possible subclones
Related to https://github.com/d3b-center/bixu-tracker/issues/848
* Environment: Cavatica
* Test files: cram/.cpn inputs

🛂 ControlFreeC I/O Port Openings

---

dev/output_vcf_pick.py
dev/vep_somatic_annotate_r93.cwl

This is part of the D3b somatic germline masking and annotation update effort. This tool runs with n updated docker containing pigz and dropping the mskcc vcf2maf tool. `dockerPull` will be updated in next PR, once it is part of vcf2maf/consensus workflow and dockerfile is approved.
See above

🎉 Add new VEP tool for future somatic processing

---

tools/bcftools_annotate.cwl
tools/gatk_variant_filter.cwl

This PR adds a tool to annotate fairly generically a vcf file using another vcf reference. It also adds a tool to fairly generically add a `FILTER` tag field for when conditions are met. These will be the new components to add to somatic caller workflows for public releases. 
Addresses # https://github.com/d3b-center/bixu-tracker/issues/818
* Environment:
* Test files:
1. [`annotation_vcf`](https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/5caf6dbde4b07ea21e2c97b2/) (tabix index or get from project), …

🎭 Germline masking tools

---

scripts/consensus_merge.py

This is to update the consensus script so that the output is created in the current working directory for compatibility with Docker and CWL, and to update the name of the output file to change the basename to the user-provided value. These are equivalent to the same changes recently made to the add_strelka2_fields script, and for the same reasons. 
I did not separately test the main functionality of the script, only that the new output file name and location were generated correctly. However, it can be tested by the same means and with the same files as https://github.com/kids-first/kf-somatic-workflow/pull/81
* Environment:
* Test files:

place output in . and fix output basename

---

scripts/consensus_merge.py

Building consensus records in pysam was adding an unused INFO field END to the VCF header. It turns out that this does not occur if you assign to VariantRecord.alleles instead of ref and alts. 
This also gets the value of the HotSpotAllele INFO field correctly. 
Fixes https://github.com/d3b-center/bixu-tracker/issues/958
* Environment: 
* python 3.8.5
* pysam 0.16.0.1 built against samtools 1.10
* Test files: see https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/9ce481b6-a3e4-4b2a-8ed4-70fdd0656366/

:bug: assign to alleles, avoid INFO END

---

scripts/hotspot.py

Well we finally got the real TSVs and the logic has been considerably fleshed out. I'll try to go over the changes as best I can:
1. Splitting up protein hotspot file submission into indels and snvs. Having separate inputs allows the script to load the positions into separate lists.
2. Ditched most of mentions of HGVSp as our inputs no longer have that as their input
3. New advanced argument for CSQ variant class; we're gonna use that to determine which list we check against
4. hs_dict[hugo] now has 3 keys to separate the different types of hotspots (snv,indel,splice) and string/regex matching to properly sort the input into these categories
5. Added a function to convert HGVSc information into HGVSp_Short information. It should provide the same functionality as this perl code:
```
if( …
```

🔥 hotspot logic

---

tools/hotspots_annotation.cwl

Python script now breaks up inputs into two fields. Adjusted CWL to reflect that.
Closes https://github.com/d3b-center/bixu-tracker/issues/999
* Environment:
* Test files:

🍌 split protein input

---

scripts/consensus_merge.py

Formerly the INFO label for hotspots in the consensus VCF was different from how it appeared in the single-caller VCFs. This is to harmonize those workflow outputs on this point. 
I believe this is a ticketless hotfix. 
* Environment: python 3.8.5, pysam 0.16.0.1, samtools 1.10
* Test files: Can be tested using inputs at 
https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/d5f469dd-fc9a-4680-bdcd-ca081ea01e04/

🔧 Hotspot -> HotSpotAllele

---

workflow/kfdrc_consensus_calling.cwl

This is create public and protected consensus outputs per #1045 and also incorporates some of the flexible-input stuff from #1021, although it does not address filtering expressions. 
Fixes https://github.com/d3b-center/bixu-tracker/issues/1045
- 
One question relates to the retained info input, which is used by both the vcf2maf and kfdrc_vcf2maf_public steps. Do these in fact use the same retained info, or are two inputs needed, one for each step? 
* Environment:
* Test files:

✨ Nhj public output

---

scripts/consensus_merge.py

This gets rid of the rigid canonical version of ALLOWED_CHROMS and adopts instead the contigs provided by the user in a BED file or, if none is provided, the contigs in the Strelka2 VCF header. Variants not in an allowed contig do not appear in the consensus output. 
Fixes https://github.com/d3b-center/bixu-tracker/issues/1085
New Dockerfile in bixtools and update to CWL tool will be needed to actually implement the change in the workflow. 
https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/d5f469dd-fc9a-4680-bdcd-ca081ea01e04/
Note VEP cache, AF VCF not needed. …

✨ Nhj consensus contigs

---

tools/expression_flatten_list.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

SBG has an issue where expression tool types need to be explicitly defined or their editor will throw errors. Our latest somatic workflow release has these errors so I fixed them.
Can't really test because the main workflow is under 🚧 by @migbro but the expressiontool errors are now gone.
* Environment:
* Test files:

🐛 etool type workaround sbg errors

---

workflow/kfdrc_consensus_calling.cwl

A small change in the output name of consensus outputs. Most PBTA naming used this convention instead of the convention used by the caller. It's a mix of fixing a minor problem and somewhat justifiable in that the normalization part really happens before. True, annotation happens but not worth changing 1000 file names.
* Environment: Cavatica
* Test files:

✏️ adjust final output name

---

README.md
sub_workflows/kfdrc_strelka2_sub_wf.cwl
tools/strelka2.cwl
workflow/kfdrc-somatic-variant-workflow.cwl
workflow/kfdrc_production_strelka2_wf.cwl

This PR addresses an edge case in which strelka2 hangs in very high depth regions. Solution employs parameter outlined here: https://github.com/Illumina/strelka/issues/168
With value in practice to be set to `--max-input-depth 10000` as recommend by @kgaonkar6 and @komalsrathi 
* Environment:
* Test files:

🤔 Added optional strelka2 params

---

workflow/kfdrc-somatic-variant-workflow.cwl

Issue discovered by @zhangb1 where setting the unpadded_capture_intervals for GATK CNV in a WGS sample would cause ControlFreeC to error. 
To circumvent the error, GATK CNV is getting its own input_interval_list workflow input. Also made the input more explicit because we have so many interval_list and capture_region inputs for this workflow that it makes my head hurt.
* Environment:
* Test files:

🐛  gatk cnv interval gets its own input

---

sub_workflows/kfdrc_gatk_cnv_somatic_pair_wf.cwl
tools/awk_min_seg_length.cwl
tools/gatk_funcotatesegments.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Two changes:
- Make GATK CNV optional depending on whether the PON is provided
- Add the QOL feature to auto generate a min segment size for funcotate segments
Closes https://github.com/d3b-center/bixu-tracker/issues/1572
* Environment:
* Test files:

🔧  gatk cnv optional

---

tools/variant_effect_predictor_105.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

New VEP tool would fail with empty call input.
I have added in an old flag from the old tool.
Basically it hard codes input as VCF instead of auto-detect.
Until we decide/want to use the tool for other input formats, this is fine.
Otherwise, in the future, we can make it an enum
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1717
* Environment:
* Test files:

🔧 added flag to fix bug when vcf is empty

---

scripts/hotspot.py
tools/hotspots_annotation.cwl

Primary Changes:
- Fixes an issue where protein position for splice hotspots was being incorrectly calculated.
- `VARIANT_CLASS: substitution` will now check against the SNV hotspots
- Now using HGVSp to determine start and end positions, by default
- Rather than requiring multi AA variants to both start and end within the hotspot we now allow them to be off by 1. They can either start 1 AA prior to the hotspot start or end 1 AA after the hotspot end (but not both!). We're adding this feature on account of the complexity of HGVSp and our uncertainty with how it exactly correlates with the MSKCC hotspot positions.
Other Changes:
- Stylistic changes to hotspot annotation CWL.
- Changed to public docker with script importing.
- Removed deprecated varaible
Closes …

🐛  hotspot splice protein pos fix

---

README.md
docs/kfdrc_annotation_wf.md
sub_workflows/kfdrc_controlfreec_sub_wf.cwl
sub_workflows/kfdrc_lancet_sub_wf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
sub_workflows/kfdrc_vardict_sub_wf.cwl
workflow/kfdrc-somatic-variant-workflow.cwl
workflow/kfdrc_annot_vcf_wf.cwl
workflow/kfdrc_consensus_calling.cwl
workflow/kfdrc_production_controlfreec_wf.cwl
workflow/kfdrc_production_lancet_wf.cwl
workflow/kfdrc_production_mutect2_wf.cwl
workflow/kfdrc_production_strelka2_wf.cwl
workflow/kfdrc_production_vardict_wf.cwl

This PR wraps up the HotSpot revolution.
- Added a disable VEP flag to annot wf, if VEP input is fine but downstream is to be repeated
- Added a custom transcript port and default input for preferred canonical isforms
- Updated documentation in annot wf about new features
- Bonus bug fix found running cwl tool of a type mismatch in controlfreec. We've never really used that input so no harm there
- Comments got removed running pub app script. Not sure how I feel about that...
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1903
* Environment: …

🚀 Annot WF Update

---

tools/gatk_filtermutectcalls.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

OPs came a across a bug in FilterMutectCalls: https://cavatica.sbgenomics.com/u/d3b-bixu-ops/sd-be4gmfqa-somatic-mutations-target-tumor/tasks/74abbcd0-99d2-4e02-8096-b1cf494235ed/
This is a known bug that was solved in GATK 4.1.5.0: https://gatk.broadinstitute.org/hc/en-us/community/posts/360057968772-FilterMutectCalls-Error-java-lang-IllegalArgumentException-log10-p-Values-must-be-non-infinite-and-non-NAN
So we're just bumping the version of that tool to 4.2.0.0
Part of https://github.com/d3b-center/bixu-tracker/issues/2135
* Environment:
* Test files:

🐛  bump filtermutectcalls docker

---

.github/scripts/workflow_to_docker_table.py

Small optimization I made over the break. Look-ups in sets are much faster than lists.
* Environment:
* Test files:

🐎  sets for faster searching

---

docs/dockers_consensus.md
docs/dockers_somatic.md
docs/kfdrc-consensus-calling.md
workflow/kfdrc_consensus_calling.cwl

Hopefully one last PR to squeeze in some doc updates since they're right there
* Environment:
* Test files:

p✏️ minor cwl doc cleanup and doc cleanup

---

tools/telomerehunter.cwl

Add Telomerehunter tool.
Part of https://d3b.atlassian.net/browse/BIXU-2290
* Environment:
* Test files:

🎉  telomerehunter init

---

docs/interval_preparation_walkthrough.md
sub_workflows/kfdrc_controlfreec_sub_wf.cwl
tools/awk_chrlen_builder.cwl

Changes:
- Update the awk_chrlen_builder tool to remove CHRs that do not appear in the b_allele file
- Update interval documentation to reflect this change
Closes https://d3b.atlassian.net/browse/BIXU-3770
* Environment:
* Test files:

:bug: remove chrlen chrs not in ballele

---

sub_workflows/kfdrc_lancet_sub_wf.cwl
sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
sub_workflows/kfdrc_vardict_sub_wf.cwl

We want to keep consistent naming for the prepass VCF when we perform reheader.
* Environment:
* Test files:

🔧  do not rename reheadered vcfs
