kids-first/kf-somatic-workflow

tools/vardictjava.cwl

Add VarDict CWL tool

---

tools/snpEff_annotate.cwl
tools/speedseq_sv_annotate.cwl
tools/variant_effect_predictor.cwl

added variant effect predictor to somatic caller set

Mb add vep

---

tools/snpEff_annotate.cwl
tools/speedseq_sv_annotate.cwl

See item #117 for tool dev details.  Runs on rabix executor, cwltool and cavatica.

Mb annot tools

---

tools/lumpy-sv.cwl
tools/lumpy-sv_germline.cwl
tools/lumpy-sv_somatic.cwl
tools/snpEff_annotate.cwl
tools/speedseq_sv_annotate.cwl
tools/variant_effect_predictor.cwl

Created tools for running lumpyexpress on germline and somatic cram/bam.

Mb add lumpy

---

tools/manta.cwl
tools/strelka2.cwl
tools/variant_effect_predictor.cwl

Mb add manta

---

dev/gatk_intervallisttool.cwl
dev/gatk_sortvcf.cwl
dev/quick_split_bed.cwl
dev/vardictjava.cwl
tools/bcbio_variant_recall_ensemble.cwl
tools/gatk_intervallisttool.cwl
tools/gatk_learnorientationbias.cwl
tools/gatk_mergevcfs.cwl
tools/gatk_sortvcf.cwl
tools/lancet.cwl
tools/vardictjava.cwl
workflow/kfdrc_mutect2_filter_support_subwf.cwl
workflow/kfdrc_mutect2_wf.cwl
workflow/kfdrc_somatic_caller_workflow.cwl
workflow/lancet_test_wf.cwl
workflow/vardict_test_wf.cwl

increased heap space for learnbias tool.  Also created a more flexible intervallisttool so that it can take bed or interval list input and also customize scatter count, bands, and set bands to 0 in exome mode.  Other dev scripts accidentally came along for the ride, but shouldn't affect current production somatic and mutect2 workflows

Mb patch mutect param

---

tools/bcbio_filter_vardict_somatic.cwl
tools/vardictjava.cwl
workflow/kfdrc_vardict_wf.cwl

Added updated vardict workflow

Mb add vardict

---

tools/bcftools_filter_vcf.cwl
tools/cnvkit_batch.cwl
tools/cnvkit_export_theta2.cwl
tools/cnvkit_import_theta2.cwl
tools/theta2_purity.cwl
workflow/kfdrc_cnvkit_batch_wf.cwl
workflow/kfdrc_cnvkit_plus_theta2.cwl
workflow/kfdrc_lancet_wf.cwl

Added cnvkit baf + theta2 workflow

Mb update cnvkit

---

tools/gatk_filter_germline_variant.cwl
workflow/kfdrc_cnvkit_batch_wf.cwl
workflow/kfdrc_cnvkit_plus_theta2.cwl
workflow/kfdrc_combined_somatic_wgs_cnv_wf.cwl
workflow/kfdrc_somatic_caller_workflow.cwl

Created controlfree + cnvkit wf, with b allele frequency filtering and theta integration for cnvkit

Mb create combined cnv wf

---

tools/smoove_lumpy.cwl

Added the smoove implementation of lumpy, with flexisbility of giving tumor and or germline bam/cram. Will fail straight away if no alignment files given.

Mb add smoove

---

tools/bedtools_intersect.cwl
tools/cnvkit_import_theta2.cwl

Resolves issue https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/669
🔧 fixed null return in js
📙 fixed description in bedtools intersect
PR template not in place yet for this repo, but the changes are cosmetic, so I will forgo, as the template is part of another PR

🔧 fix technical bugs

---

README.md
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl

This PR has documentation changes for the new WGS/WXS workflow added recently.
* Environment: NA
* Test files: NA

📚 added documentation for combined wf

---

workflow/kfdrc_production_cnvkit_wf.cwl
workflow/kfdrc_production_controlfreec_wf.cwl
workflow/kfdrc_production_lancet_wf.cwl
workflow/kfdrc_production_manta_wf.cwl
workflow/kfdrc_production_mutect2_wf.cwl
workflow/kfdrc_production_strekla2_wf.cwl
workflow/kfdrc_production_theta2_wf.cwl
workflow/kfdrc_production_vardict_wf.cwl

This PR sets out to create standalone public apps for all the callers that are used in our production somatic calling workflow. 
Part of https://github.com/d3b-center/bixu-tracker/issues/593
* Environment: Cavatica, cwltool 3.0.20200324120055
* Test files: See Cavatica tests

🧍Standalone Caller Apps

---

sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
tools/manta.cwl
tools/strelka2.cwl
workflow/kfdrc_production_lancet_wf.cwl
workflow/kfdrc_production_manta_wf.cwl
workflow/kfdrc_production_somatic_variant_cnv_wf.cwl
workflow/kfdrc_production_strekla2_wf.cwl

The main changes in this PR focus on collecting small indels from Manta and using those to inform Strelka. To accomplish this change, I've done the following:
1. Manta tool moves the small indel file and index to the working directory, renaming them in the process, then I collect those files as a single output (vcf file with secondary index)
1. Strelka tool now has an optional file input for the small indels as well as a toggle for using that file. If the file is provided and the user says to use the file, it will be used. In all other cases, the file will not be used.
1. Manta subwf and prod wf now collect the new small indel output from the Manta tool and returns it
1. Strelka subwf and prod wf now have an optional Manta small indel input and toggle for that file that it can hand to the …

✨ manta small indels inform strelka calling

---

tools/ubuntu_ratio2seg.cwl

Task https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-zxjffmef-somatic-mutations-wxs-tumor/tasks/e887f143-8113-42f8-8c08-4b3d08bbf647/stats/ was failing after ControlFreeC ran, at the custom script to create seg files step. Unexpected input of `-0` as a median ratio value was not handled. In this PR, I have change the evals to use `float` and `int` comparisons instead of relying on exact string match.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/805
I downloaded the temp intermediate file (ControlFreeC ratio) that I copied into the project here: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-zxjffmef-somatic-mutations-wxs-tumor/files/5f6e0f97e4b05495d8232ce1/. I then downloaded it to a local ec2 instance, copied …

🔧 ControlFreeC Seg File Tool Fix

---

tools/prep_mnp_variants.cwl
workflow/kfdrc_consensus_calling.cwl

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes https://github.com/d3b-center/bixu-tracker/issues/898
- I ran the whole consensus workflow with changes on EC2 instance with cwltool
- Also works on Cavatica: https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/c146b686-2ec2-4534-9880-bea3209488c4/#
* Environment: cwltool 3.0.20201203173111
* Test files: See Cavatica task above

requirements needed by cwltool and chr() calls instead of \t, \t

---

scripts/hotspot.py

This PR adds a script to flag hotspots in VCFs output from the somatic workflows.
Part of https://github.com/d3b-center/bixu-tracker/issues/854
**Test Configuration**: python --hotspots Inputs/known_somatic_sites.bed --vcf Inputs/f848774b-b04b-493d-859b-52c0c8184333.mutect2.PASS.vep.vcf.gz
* Environment: Python3.6.9
Pip freeze:
backcall==0.2.0
decorator==4.4.2
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.18.0
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.10
ptyprocess==0.7.0
Pygments==2.7.4
pysam==0.16.0.1
six==1.15.0
traitlets==4.3.3
wcwidth==0.2.5
* Test files: All the input VCFs here: …

✨ script to flag hotspots

---

tools/gatk_mergemutectstats.cwl

fix the id for `/tools/gatk_mergemutectstats.cwl`
#75 
not tested, as it's only changed the tool id
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] New and existing unit tests pass locally with my changes~
~- [ ] Any dependent changes have been merged and published in downstream modules~

🔧  fix id in gatk_mergemutectstats.cwl 

---

scripts/add_strelka2_fields.py

The output of this script was formerly saved in the same directory as the input, which caused a problem running in a container with cwltool
* Environment: 
* Python 3.8.5
* pysam 0.16.0
* underlying samtools 1.10
* Test files:
* Strelka2 VCF: https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/5ffdf91ce4b0a6d32f329e6b/
* tumor name BS_F0GNWEJJ
* normal name BS_F5EX3ZY5

change output directory to . and apply new output_basename

---

tools/add_strelka2_fields.cwl

This is a CWL tool wrapping the script that adds canonical VCF fields to Strelka2 output.
- https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/7325b1d2-cc67-4d43-9966-4be69a7a1791/
* Environment: cwltool 3.0.20201203173111
* Test files:
* Strelka2 VCF: https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/5ffdf91ce4b0a6d32f329e6b/
* tumor name BS_F0GNWEJJ
* normal name BS_F5EX3ZY5
* output_basename: any

Nhj strelka2 fields tool

---

README.md
tools/tabix_index.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Optional indexing created a scenario where not providing the b allele file would cause a failure. 
* Environment:
* Test files:

🐛 b allele truly optional

---

scripts/consensus_merge.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Closes https://github.com/d3b-center/bixu-tracker/issues/966
I only tested the error handling for invalid values of the new option. The script has been tested before and will be re-tested at CWL time with real inputs if that's ok. I don't really want to pull down a whole cram just to see if this number thing works. 
* Environment:
* Python 3.8.5
* Test files:

✨ made callers for consensus optional w/ default 2

---

sub_workflows/kfdrc_run_theta2_sub_wf.cwl

Updated theta2 subwf name to be clearer, and added a simple doc description.
NA, simple ID and doc change
* Environment:
* Test files:

🔧  fixed/clarified theta2 subwf name

---

scripts/hotspot.py

Updates the hotspot scripts to handle newly defined inputs.
Closes https://github.com/d3b-center/bixu-tracker/issues/952
* Environment: docker pull dmiller15/hotspots:0.1.0
* Test files:
- Hotspot examples here: https://github.com/d3b-center/bixu-tracker/issues/952
- VCF: https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/6047f398252bc31f2a8c8678/

🔧 update hotspots script

---

tools/hotspots_annotation.cwl

Part of https://github.com/d3b-center/bixu-tracker/issues/968
* Environment: cwltool 3.0.20210124104916, Cavatica
* Test files: See Cavatica tests

✨ add hotspot tool

---

tools/consensus_merge.cwl

CWL tool wrapping the script that merges the single-caller vcfs in the somatic consensus workflow. 
https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/928156ec-8ad9-4860-b20e-fff3ecda0ee6/
Updated run:
https://cavatica.sbgenomics.com/u/nathanj/test-project/tasks/9ce481b6-a3e4-4b2a-8ed4-70fdd0656366/
* Environment: cwltool 3.0.20201203173111
* Test files: see Cavatica task above

:sparkles: CWL tool for consensus script

---

workflow/kfdrc_consensus_calling.cwl

This is a workflow that covers the lower "Consensus calling" portion of the diagram at:
https://whimsical.com/somatic-workflow-5AdRxyhakEwGRakCL5wbQf
It creates a single somatic consensus VCF and MAF from individual-caller VCFs and various other inputs.
This creates only the 'protected release' files, not the 'public release' ones from which FILTERed variants have been dropped as far as I know. 
This may not work locally without a change to `vep_somatic_annotate_r93.cwl` which is part of #95 but has not been merged at the time of this writing. I made the change on my branch for testing purposes but did not push it. The workflow appears to have worked on Cavatica even though I do not believe the change is reflected there. A warning may occur until this fix is in. 
Fixes # …

✨ Consensus workflow update

---

workflow/kfdrc-somatic-variant-workflow.cwl

Updates suggest file paths
Part of https://github.com/d3b-center/bixu-tracker/issues/1027
* Environment:
* Test files:

🐛 update suggested file paths

---

dev/temp_norm_annot_patch_wf.cwl
docs/temp_norm_annot_patch_wf.md
sub_workflows/kfdrc_annot_vcf_sub_wf.cwl
tools/kf_mskcc_vcf2maf.cwl

This updates the dev workflow for ops to use for bringing our individual caller outputs to spec. I also added a doc to the docs folder to explain what is done and what inputs should be used.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/818
* Environment: cavatica
* Test files:
```
../sub_workflows/kfdrc_annot_vcf_sub_wf.cwl:112:8: Source 'filtered_vcf' of type "File" may be
incompatible
../sub_workflows/kfdrc_annot_vcf_sub_wf.cwl:118:7:   with sink 'input_vcf' of type "File"
../sub_workflows/kfdrc_annot_vcf_sub_wf.cwl:10:29: Source …
```

🔓⬆️ Update annotation workflow

---

tools/theta2_purity.cwl

This just points the tool at the docker representing the speeded-up version of THetA2. 
This is the final step in resolving https://github.com/d3b-center/bixu-tracker/issues/1053 but that one is closed and there is currently no ticket for this in particular. 
* Environment:
* Test files:

🐳  point at updated docker

---

docs/kfdrc-consensus-calling.md
workflow/kfdrc_consensus_calling.cwl

Fixed file output naming. Also, after field testing, will open up at the wf level the memory adjustment that @NHJohnson made available at the tool level. A task ran out of memory, so this will help for when it happens.
Fixes # Hot Fix
* Environment:
* Test files:

🛠 Minor improvements

---

tools/consensus_merge.cwl
workflow/kfdrc_consensus_calling.cwl

Last time, here's one that has the same changes as #118 but with commits that are both untangled and adequately descriptive. 
* Environment:
* Test files:

Nhj consensus contigsc

---

sub_workflows/kfdrc_cnvkit_sub_wf.cwl
tools/gatk_filter_germline_variant.cwl
workflow/kfdrc-somatic-variant-workflow.cwl
workflow/kfdrc_production_cnvkit_wf.cwl

We make pretty pictures. Let the users see them.
* Environment:
* Test files:

🖼 pretty cnvkit pictures

---

README.md
tools/cnvkit_batch.cwl
tools/expression_flatten_list.cwl
workflow/kfdrc-somatic-variant-workflow.cwl
workflow/kfdrc_production_cnvkit_theta2_wf.cwl

This wf was created so that Bix Ops can bring the Maris study up to spec with CNVkit calls. In the process of creating it, I also added a big fix. Once this and PR #127 are approved, I will cut a new release.
* Environment:
* Test files:

🎉 Added a combined cnvkit + theta2 wf

---

sub_workflows/kfdrc_annot_vcf_sub_wf.cwl
sub_workflows/kfdrc_controlfreec_sub_wf.cwl
sub_workflows/kfdrc_lancet_sub_wf.cwl
sub_workflows/kfdrc_manta_sub_wf.cwl
sub_workflows/kfdrc_mutect2_filter_support_subwf.cwl
sub_workflows/kfdrc_mutect2_sub_wf.cwl
sub_workflows/kfdrc_run_theta2_sub_wf.cwl
sub_workflows/kfdrc_strelka2_sub_wf.cwl
sub_workflows/kfdrc_vardict_sub_wf.cwl
tools/add_strelka2_fields.cwl
tools/bcftools_annotate.cwl
tools/control_freec_mini_pileup.cwl
tools/expression_flatten_file_list.cwl
tools/gatk_filtermutectcalls.cwl
tools/gatk_getpileupsummaries.cwl
tools/gatk_intervallisttool.cwl
tools/gatk_learnorientationbias.cwl
tools/gatk_variant_filter.cwl
tools/kf_mskcc_vcf2maf.cwl
tools/manta.cwl
tools/mode_list_selector.cwl
tools/strelka2.cwl
tools/vep_somatic_annotate_r93.cwl
workflow/kfdrc-somatic-variant-workflow.cwl
workflow/kfdrc_consensus_calling.cwl
workflow/kfdrc_production_controlfreec_wf.cwl
workflow/kfdrc_production_lancet_wf.cwl
workflow/kfdrc_production_mutect2_wf.cwl
workflow/kfdrc_production_strelka2_wf.cwl
workflow/kfdrc_production_vardict_wf.cwl

Looks like a lot but for the most part this is just adding quotes to the input/output "types" as well as the "sbg:" tags. Outside of that there are some other changes:
1. Adds expression_flatten_file_list to where I explicitly state the input/output types so the workflows can pass cwltool and sbpack validation
1. Adds a new mode_list_selector cwl for the explicit handling of file list inputs/outputs
1. Changes the existing mode_selector tool to handle file inputs/outputs
1. Change the subworkflows and workflows to use the appropriate version of the above three
* Environment: cwltool 3.1.20211020155521 and sbpack v2020.10.05
* Test files:

🎨  sbpack fixes

---

sub_workflows/kf_cnv_somatic_pair_wf.cwl
sub_workflows/kfdrc_gatk_cnv_somatic_pair_wf.cwl
tools/gatk_annotateintervals.cwl
tools/gatk_callcopyratiosegments.cwl
tools/gatk_collectalleliccounts.cwl
tools/gatk_collectreadcounts.cwl
tools/gatk_createreadcountpanelofnormals.cwl
tools/gatk_denoisereadcounts.cwl
tools/gatk_funcotatesegments.cwl
tools/gatk_modelsegments.cwl
tools/gatk_plotdenoisedcopyratios.cwl
tools/gatk_plotmodeledsegments.cwl
tools/gatk_preprocessintervals.cwl
tools/tar.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Ported over GATK CNV tools and somatic pair workflow. 
In terms of review, we know the tools and sub_workflow work. Point of emphasis should be on the integration of the sub_workflow into the grand somatic workflow. Critiques of input names, output names, and which inputs and outputs should be made available to the user at the kfdrc-somatic-workflow level. 
Since updated to use the most recent GATK release (log4j fixes)
Merge after #129 
Documentation will be updated in a future PR.
* Environment: cwltool 3.1.20211020155521, sbpack v2020.10.05
* Test files:

🎉  ported over gatk cnv tools

---

README.md
workflow/kfdrc-somatic-variant-workflow.cwl

Adds documentation for GATK CNV tools and workflow.
* Environment: cwltool 3.1.20211020155521
* Test files:

:books: update docs to with GATK CNV info

---

README.md
tools/annotsv.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Merge after #131
Part of https://github.com/d3b-center/bixu-tracker/issues/1192
* Environment: cavatica
* Test files:

🎉 Add AnnotSV

---

docs/kfdrc-consensus-calling.md
workflow/kfdrc_consensus_calling.cwl

Simple documentation update for public app release accuracy
* Environment:
* Test files:
- [x I have committed any related changes to the PR

✏️ update consensus readme, doc, and version

---

workflow/kfdrc_annot_vcf_wf.cwl

Explained in the ticket link below, fixes behavior of disable VEP flag
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1976
* Environment:
* Test files:

🔧 fix buggy flag behavior for skip vep flag

---

docs/kfdrc_gatk_create_cnv_pon_wf.md
workflow/kfdrc_gatk_create_cnv_pon_wf.cwl

Updating readme to include more of our process.
Closes https://github.com/d3b-center/bixu-tracker/issues/1923
* Environment:
* Test files:

📚  update PON readme

---

README.md
workflow/kfdrc-somatic-variant-workflow.cwl

Some data we receive are not suitable for certain types of analysis. For example, some panels are too small for reliable CNV and SV calls. This PR introduces as CNV and SV class switch. Also tweaked the apps pub app to allow slightly wider strings. If we like that, I can PR that too
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2112
**Note** During testing I had a bug in the Run all in that I put the conditional in samtools cram to bam step, forgetting it was needed for vardict. So, when I a re-ran to demonstrate, I fixed that bug, but that difference caused …

🚦 Add CNV SV Switches

---

tools/preprocess_lancet_intervals.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Noticed that the Lancet BED creation was silently failing. To address this I modified the tool to:
1. actually pipefail. the previous implementation does not work without `shellQuote: true` for reasons outlined here: https://github.com/d3b-center/bixu-tracker/issues/630
2. add `switch-BEDOPS-binary-type --megarow;` to the script so that we're always using the correct binary for files with large rows
3. cleaned up echo commands for uniformity and error logging
4. cleaned up gunzip/bedops commands so the command line is human readable
Part of https://github.com/d3b-center/bixu-tracker/issues/2143
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …

🐛  fix lancet interval silent failure

---

sub_workflows/kfdrc_vardict_sub_wf.cwl
sub_workflows/prepare_regions.cwl
tools/clt_pass_file.cwl
tools/control-freec-11-6-sbg.cwl
tools/gatk_bedtointervallist.cwl
tools/gatk_filtermutectcalls.cwl
tools/gatk_intervallisttobed.cwl
tools/gatk_intervallisttools.cwl
tools/vardictjava.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

This PR modifies unifies our approach to intervals.
Part of https://github.com/d3b-center/bixu-tracker/issues/2132
* Environment:
* Test files:

🐎 unify somatic intervals

---

workflow/kfdrc-somatic-variant-workflow.cwl

remove index steps;
add dict and fai expressions
Change in our approach to reference inputs that have indexes:
- Suggested file now pulls in associated indices for references
- Add secondaryFile requirements to prevent users providing unindexed results
- Remove indexing and pointless reference preparation steps from beginning of workflow 
Closes https://github.com/d3b-center/bixu-tracker/issues/2136
* Environment:
* Test files:

🐎 add secondaryFiles to inputs;

---

sub_workflows/kfdrc_manta_sub_wf.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Small change to move annotSV inside the manta subworkflow.
Closes https://github.com/d3b-center/bixu-tracker/issues/2137
* Environment:
* Test files:

🔧  put annotsv in manta subwf

---

README.md
docs/interval_preparation_walkthrough.md
sub_workflows/kfdrc_cnvkit_sub_wf.cwl
sub_workflows/kfdrc_controlfreec_sub_wf.cwl
tools/awk_chrlen_builder.cwl
tools/cnvkit_access.cwl
tools/cnvkit_batch.cwl
workflow/kfdrc-somatic-variant-workflow.cwl

Simplifies the CNV interval inputs:
- Removes chrLen file input
- New region creation specifically for CNV
- Workflow builds chrLen file based on new regions from above
- Added a step to make a custom access file for CNVkit using the cnv_blacklist_regions
Closes https://github.com/d3b-center/bixu-tracker/issues/2173
* Environment:
* Test files:

🐎  streamline cnv intervals

---

tools/control_freec_mini_pileup.cwl
tools/gatk_selectvariants.cwl
tools/vardictjava.cwl

Getting rid of improperly formatted pipefail declarations for tools in the somatic workflow.
Closes https://github.com/d3b-center/bixu-tracker/issues/2199
* Environment:
* Test files:

🐛  fix pipefails

---

.github/scripts/workflow_to_docker_table.py

Found this bug when porting this tool to the alignment workflow.
* Environment:
* Test files:

🐛  more robust run checking

---

docs/interval_preparation_walkthrough.md

Quick broken link.
Closes https://github.com/d3b-center/bixu-tracker/issues/2285
* Environment:
* Test files:

📚  fix broken link

---

workflow/kfdrc-somatic-variant-workflow.cwl

Quick bump of the release number for upcoming release.
Part of https://d3b.atlassian.net/browse/BIXU-3771
* Environment:
* Test files:

:bookmark: bump release number
